"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Locale = "tr" | "en" | "ku";

interface LanguageContextType {
    locale: Locale;
    setLocale: (locale: Locale) => void;
    t: (key: string) => string;
}

const translations: Record<Locale, Record<string, string>> = {
    tr: {
        "nav.university": "Üniversitemiz",
        "nav.academic": "Akademik",
        "nav.student": "Öğrenci",
        "nav.research": "Araştırma",
        "nav.hospital": "Hastane",
        "nav.staff": "Personel Rehberi",
        "nav.candidate": "Aday Öğrenci",
        "search.placeholder": "Üniversitede arayın...",
        "search.trigger": "Neyi arıyorsunuz? (Bölüm, Haber, Birim...)",
        "search.noResults": "Sonuç bulunamadı",
        "search.quickSearch": "Hızlıca Arayın",
        "search.description": "Bölümleri, haberleri veya üniversite birimlerini anında bulun.",
        "search.select": "Seç",
        "search.navigate": "Gezin",
        "bot.greeting": "Merhaba! 👋 Ben Dicle Üniversitesi Akıllı Asistanı. Size nasıl yardımcı olabilirim?",
        "bot.online": "Çevrimiçi",
        "bot.placeholder": "Bir şeyler sorun...",
        "bot.food": "Yemek Listesi",
        "bot.calendar": "Akademik Takvim",
        "bot.transport": "Ulaşım",
        "uni.pastFuture": "Köklü Geçmiş, Güçlü Gelecek",
        "uni.intro1": "Dicle Üniversitesi, 1973 yılında kurulan ve Güneydoğu Anadolu Bölgesi'nin eğitim, bilim ve sağlık üssü olma misyonunu taşıyan köklü bir devlet üniversitesidir. Tarihi dokusu, geniş kampüs olanakları ve uzman akademik kadrosuyla öğrencilerine evrensel standartlarda bir eğitim sunmaktadır.",
        "uni.intro2": "Bünyesinde barındırdığı 15 Fakülte, 12 Meslek Yüksekokulu, 4 Yüksekokul ve 1 Konservatuvar ile bölgesel kalkınmaya öncülük etmekte, bilimsel araştırmalarıyla ulusal ve uluslararası alanda başarılarını sürdürmektedir.",
        "uni.corporate": "Kurumsal Bilgiler",
        "uni.corporateDesc": "Üniversitemizin {title} hakkında detaylı bilgiler.",
        "uni.adminStructure": "İdari Yapı",
        "uni.estYear": "Kuruluş Yılı",
        "uni.facultyCount": "Fakülte",
        "uni.studentCount": "Öğrenci",
        "uni.academicStaff": "Akademik Personel",
        "page.underConstruction": "Bu sayfa hazırlanıyor",
        "page.underConstructionDesc": "Aradığınız içerik şu anda güncellenmektedir. Lütfen daha sonra tekrar ziyaret ediniz.",
        "footer.address": "Dicle Üniversitesi Kampüsü, 21280 Sur / DİYARBAKIR",
        "footer.contact": "İletişim",
        "footer.quickLinks": "Hızlı Erişim",
        "footer.academic": "Akademik",
        "footer.about": "Hakkımızda",
        "footer.mission": "Misyon & Vizyon",
        "footer.press": "Basın Merkezi",
        "footer.virtualTour": "Sanal Kampüs Turu",
        "footer.map": "İnteraktif Harita",
        "footer.calendar": "Akademik Takvim",
        "footer.faculties": "Fakülteler",
        "footer.institutes": "Enstitüler",
        "footer.schools": "Yüksekokullar",
        "footer.researchCenters": "Araştırma Merkezleri",
        "footer.hospitalLink": "DÜ Hastanesi",
        "footer.alumni": "Mezun Platformu",
        "footer.copyright": "Dicle Üniversitesi Bilgi İşlem Daire Başkanlığı.",
        "home.newsTitle": "Duyurular & Haberler",
        "home.studentLife": "Öğrenci Yaşamı",
        "home.foodMenu": "Günün Yemek Menüsü",
        "home.events": "Etkinlik Takvimi",
        "calendar.title": "Etkinlik Takvimi",
        "calendar.noEvents": "Bu tarihte planlanmış etkinlik bulunmuyor.",
        "calendar.daySuffix": " Etkinlikleri",
        "calendar.monthEvents": "Bu Ayın Etkinlikleri",
        "calendar.event": "ETKİNLİK",
        "day.sun": "Pz",
        "day.mon": "Pt",
        "day.tue": "Sa",
        "day.wed": "Ça",
        "day.thu": "Pe",
        "day.fri": "Cu",
        "day.sat": "Ct",
        "food.noMenu": "Bugün için yemek listesi bulunamadı.",
        "food.title": "Günün Menüsü",
        "food.soup": "Çorba",
        "food.main": "Ana Yemek",
        "food.side": "Tamamlayıcı",
        "food.extra": "Tatlı/Meyve",
        "food.calories": "Toplam Kalori",
        "home.quickAccess": "Hızlı Erişim",
        "home.stats": "Sayılarla Dicle",
        "home.social": "Sosyal Medya",
        "home.library": "Kütüphane",
        "tab.haber": "Haberler",
        "tab.duyuru": "Duyurular",
        "tab.etkinlik": "Etkinlikler",
        "hero.title": "Geleceği Şekillendiren Bilim Üssü",
        "hero.subtitle": "50 yıllık tecrübemizle, evrensel değerlerle donatılmış bireyler yetiştiriyoruz.",
        "hero.cta": "Kampüsü Keşfet",
        "hero.admission": "Kayıt Rehberi",
        "hero.universityDesc": "Modern yönetim anlayışı, geniş yeşil alanları ve tarihi dokusuyla eğitimin kalbi.",
    },
    en: {
        "nav.university": "Our University",
        "nav.academic": "Academic",
        "nav.student": "Student",
        "nav.research": "Research",
        "nav.hospital": "Hospital",
        "nav.staff": "Staff Directory",
        "nav.candidate": "Candidate Student",
        "search.placeholder": "Search in university...",
        "search.trigger": "What are you looking for? (Department, News, Unit...)",
        "search.noResults": "No results found",
        "search.quickSearch": "Quick Search",
        "search.description": "Find departments, news or university units instantly.",
        "search.select": "Select",
        "search.navigate": "Navigate",
        "bot.greeting": "Hello! 👋 I am Dicle University Smart Assistant. How can I help you?",
        "bot.online": "Online",
        "bot.placeholder": "Ask something...",
        "bot.food": "Food Menu",
        "bot.calendar": "Academic Calendar",
        "bot.transport": "Transportation",
        "uni.pastFuture": "Rooted Past, Strong Future",
        "uni.intro1": "Dicle University is a well-established state university founded in 1973 with the mission of being the education, science, and health base of the Southeastern Anatolia Region. It offers education at universal standards to its students with its historical texture, wide campus opportunities, and expert academic staff.",
        "uni.intro2": "With 15 Faculties, 12 Vocational Schools, 4 Schools, and 1 Conservatory, it leads regional development and continues its success in national and international fields with its scientific research.",
        "uni.corporate": "Corporate Information",
        "uni.corporateDesc": "Detailed information about our university's {title}.",
        "uni.adminStructure": "Administrative Structure",
        "uni.estYear": "Foundation Year",
        "uni.facultyCount": "Faculties",
        "uni.studentCount": "Students",
        "uni.academicStaff": "Academic Staff",
        "page.underConstruction": "This page is under construction",
        "page.underConstructionDesc": "The content you are looking for is currently being updated. Please visit again later.",
        "footer.address": "Dicle University Campus, 21280 Sur / DIYARBAKIR",
        "footer.contact": "Contact",
        "footer.quickLinks": "Quick Links",
        "footer.academic": "Academic",
        "footer.about": "About Us",
        "footer.mission": "Mission & Vision",
        "footer.press": "Press Center",
        "footer.virtualTour": "Virtual Campus Tour",
        "footer.map": "Interactive Map",
        "footer.calendar": "Academic Calendar",
        "footer.faculties": "Faculties",
        "footer.institutes": "Institutes",
        "footer.schools": "Schools",
        "footer.researchCenters": "Research Centers",
        "footer.hospitalLink": "DU Hospital",
        "footer.alumni": "Alumni Platform",
        "footer.copyright": "Dicle University IT Department.",
        "home.newsTitle": "Announcements & News",
        "home.studentLife": "Student Life",
        "home.foodMenu": "Daily Food Menu",
        "home.events": "Event Calendar",
        "calendar.title": "Event Calendar",
        "calendar.noEvents": "No events scheduled for this date.",
        "calendar.daySuffix": " Events",
        "calendar.monthEvents": "Events This Month",
        "calendar.event": "EVENT",
        "day.sun": "Sun",
        "day.mon": "Mon",
        "day.tue": "Tue",
        "day.wed": "Wed",
        "day.thu": "Thu",
        "day.fri": "Fri",
        "day.sat": "Sat",
        "food.noMenu": "No food menu found for today.",
        "food.title": "Daily Menu",
        "food.soup": "Soup",
        "food.main": "Main Course",
        "food.side": "Side Dish",
        "food.extra": "Dessert/Fruit",
        "food.calories": "Total Calories",
        "home.quickAccess": "Quick Access",
        "home.stats": "Dicle in Numbers",
        "home.social": "Social Media",
        "home.library": "Library",
        "tab.haber": "News",
        "tab.duyuru": "Announcements",
        "tab.etkinlik": "Events",
        "hero.title": "The Science Base Shaping the Future",
        "hero.subtitle": "With 50 years of experience, we raise individuals equipped with universal values.",
        "hero.cta": "Discover Campus",
        "hero.admission": "Admission Guide",
        "hero.universityDesc": "The heart of education with its modern management approach, vast green areas, and historical texture.",
    },
    ku: {
        "nav.university": "Zankoya Me",
        // ... (lines 184-263 omitted for brevity in replace block context, but I will target specific insertion points)
        // I need to do this carefully. I'll use multi_replace or separate replace calls if needed.
        // Actually, I can just target the end of 'en' block and 'ku' block.

        "nav.academic": "Akademîk",
        "nav.student": "Xwendekar",
        "nav.research": "Lêkolîn",
        "nav.hospital": "Nexweşxane",
        "nav.staff": "Rêberê Personelan",
        "nav.candidate": "Xwendekarê Berendam",
        "search.placeholder": "Li zankoyê bigere...",
        "search.trigger": "Tu li çi digerî? (Beş, Nûçe, Yekîn...)",
        "search.noResults": "Tu encam nehatin dîtin",
        "search.quickSearch": "Lêgerîna Bilez",
        "search.description": "Beş, nûçe an yekîneyên zankoyê tavilê bibînin.",
        "search.select": "Hilbijêre",
        "search.navigate": "Bigere",
        "bot.greeting": "Silav! 👋 Ez Asîstanê Zîrek ê Zankoya Dîclê me. Ez dikarim çawa alîkariya we bikim?",
        "bot.online": "Serhêl",
        "bot.placeholder": "Tiştekî bipirse...",
        "bot.food": "Lîsteya Xwarinê",
        "bot.calendar": "Salnameya Akademîk",
        "bot.transport": "Veguhastin",
        "uni.pastFuture": "Rabirdûyeke Kûr, Pêşerojeke Bihez",
        "uni.intro1": "Zankoya Dîclê zankoyeke dewletê ya kûr e ku di sala 1973an de bi wezîfeya perwerdehiyê hatiye damezrandin. Bi tevna xwe ya dîrokî, derfetên kampusa fireh û kadroya akademîk a pispor, perwerdehiyê li gorî standardên gerdûnî pêşkêşî xwendekarên xwe dike.",
        "uni.intro2": "Bi 15 Fakulte, 12 Dibistanên Bilind ên Pîşeyî, 4 Dibistanên Bilind û 1 Konservatuarê ve, pêşengiya pêşkeftina herêmî dike û serkeftinên xwe di qadên neteweyî û navneteweyî de bi lêkolînên zanistî didomîne.",
        "uni.corporate": "Agahiyên Sazûmanî",
        "uni.corporateDesc": "Agahiyên berfireh derbarê {title} ya zankoya me de.",
        "uni.adminStructure": "Sazûmana Îdarî",
        "uni.estYear": "Sala Damezrandinê",
        "uni.facultyCount": "Fakulte",
        "uni.studentCount": "Xwendekar",
        "uni.academicStaff": "Kadroya Akademîk",
        "page.underConstruction": "Ev rûpel tê amadekirin",
        "page.underConstructionDesc": "Naveroka ku hûn lê digerin niha tê nûkirin. Ji kerema xwe şûnde dîsa serdanê bikin.",
        "footer.address": "Kampusa Zankoya Dîcleyê, 21280 Sûr / DIYARBEKIR",
        "footer.contact": "Têkilî",
        "footer.quickLinks": "Gihîştina Bilez",
        "footer.academic": "Akademîk",
        "footer.about": "Derbarê Me de",
        "footer.mission": "Mîsyon û Vizyon",
        "footer.press": "Navenda Çapemeniyê",
        "footer.virtualTour": "Tûra Kampusê ya Virtual",
        "footer.map": "Nexşeya Înteraktîf",
        "footer.calendar": "Salnameya Akademîk",
        "footer.faculties": "Fakulte",
        "footer.institutes": "Enstîtû",
        "footer.schools": "Dibistanên Bilind",
        "footer.researchCenters": "Navendên Lêkolînê",
        "footer.hospitalLink": "Nexweşxaneya Dîcleyê",
        "footer.alumni": "Platforma Mezûnan",
        "footer.copyright": "Serokatiya Daîreya Agahînasî ya Zankoya Dîclê.",
        "home.newsTitle": "Daxuyanî û Nûçe",
        "home.studentLife": "Jiyana Xwendekaran",
        "home.foodMenu": "Lîsteya Xwarinê ya Rojê",
        "home.events": "Salnameya Çalakiyan",
        "calendar.title": "Salnameya Çalakiyan",
        "calendar.noEvents": "Di vê dîrokê de tu çalakî nehatine plankirin.",
        "calendar.daySuffix": " Çalakiyên ",
        "calendar.monthEvents": "Çalakiyên Vê Mehê",
        "calendar.event": "ÇALAKÎ",
        "day.sun": "Yek",
        "day.mon": "Duş",
        "day.tue": "Sêş",
        "day.wed": "Çar",
        "day.thu": "Pên",
        "day.fri": "În",
        "day.sat": "Şem",
        "food.noMenu": "Ji bo îro lîsteya xwarinê nehat dîtin.",
        "food.title": "Menuya Rojê",
        "food.soup": "Şorbe",
        "food.main": "Xwarina Sereke",
        "food.side": "Xwarina Alîkar",
        "food.extra": "Şîranî/Fêkî",
        "food.calories": "Kaloriya Giştî",
        "home.quickAccess": "Gihîştina Bilez",
        "home.stats": "Dîcle bi Hejmaran",
        "home.social": "Medyaya Civakî",
        "home.library": "Pirtûkxane",
        "tab.haber": "Nûçe",
        "tab.duyuru": "Daxuyanî",
        "tab.etkinlik": "Çalakî",
        "hero.title": "Bingeha Zanistê ya ku Pêşerojê Şikil Dide",
        "hero.subtitle": "Bi azmûna xwe ya 50 salî, em kesên ku bi nirxên gerdûnî hatine xemilandin perwerde dikin.",
        "hero.cta": "Kampusê Keşf Bike",
        "hero.admission": "Rêberê Qeydê",
        "hero.universityDesc": "Bi nêzîkatiya xwe ya rêveberiya nûjen, qadên kesk ên berfireh û tevna xwe ya dîrokî, dilê perwerdehiyê ye.",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [locale, setLocale] = useState<Locale>("tr");

    const t = (key: string) => {
        return translations[locale][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
};
